# Generated by Django 4.0.2 on 2022-02-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(help_text='Nome da empresa.', max_length=155, verbose_name='Nome'),
        ),
    ]
